scripts/configure.sh
volumio/etc/shairport-sync.conf
volumio/etc/shairport-sync.conf.tmpl
volumio/lib/systemd/system/airplay.service

configure.sh: set proper permissions on /etc/shairport* configuration files (template + configuration file)
/etc/shairport-sync.conf and /etc/shairport-sync.conf.tmpl: the TMPL is used by volumio airplay plugin to create runtime airplay configuration with ALSA and system name
airplay.service: shairport systemd configuration

Shairport as a service

---

scripts/initramfs/init
scripts/odroidcimage.sh
scripts/odroidx2image.sh
scripts/odroidxu4config.sh
scripts/odroidxu4image.sh

Changed the XU4 build to "standard" Volumio 2 requirements (initrd/ SD card resizing/ overlayfs/ squashfs and init- or remote-updater).
Reorganized odroid repo with one tarball per platform.

xu4 with initramsfs and overlay/ reorganized odroid repo

---

scripts/odroidcconfig.sh

Currently only works for Odroid C2, C1+ is to follow later.
(building with this script requires new Odroid C2 kernel --version 20160315-- to be cloned from repo!)

Add loadable sound modules to /etc/modules

---

build.sh
scripts/initramfs/init

This fixes a timing problem in the initrd by repeating the "mdev -s" command in case /dev/mmcblk0p2 cannot be detected. The fixed sleep period could be removed.
The build.sh script was adapted to make sure, /etc/os-release has the latest info related to the device and version being built. Especially important when the same rootfs is used for several devices.

initramfs fix plus small build.sh improvement

---

scripts/raspberryconfig.sh

Root is currently needed to control GPIO pins. This fix solves it.
I have tested this on RPi 2 B. The gpio control files in /sys/class/gpio are correctly owned by group 'gpio' with the fix applied.
The fix is from [https://github.com/raspberrypi/linux/issues/1117#issuecomment-134227514](https://github.com/raspberrypi/linux/issues/1117#issuecomment-134227514). I was told it was already applied but can not find it anywhere on here.

GPIO pin permission fix

---

scripts/raspberryimage.sh

At this point in the process, /mnt/volumio/rootfs/opt (copied from build/arm/root/opt) is empty.
Create the destination directory before copying the dtoverlay programs into it.
Without this change I get this error during build:
```
echo "Custom dtoverlay pre and post"
cp: target ‘/mnt/volumio/rootfs/opt/vc/bin/’ is not a directory
```

Make sure the dtoverlay binaries have somewhere to go

---

build.sh
scripts/cuboxiconfig.sh
scripts/cuboxiimage.sh
scripts/initramfs/init
scripts/initramfs/init-x86
scripts/x86.sh
scripts/x86config.sh

x86: this will allow you to boot a different build from usb after you cloned the original to the pc's hdd. However, after you cloned and you try to boot the same build from usb, it will always take the pc's hdd. Which is ok in most cases. The only real way of solving it, would be to make either the uuid or label unique on first boot or after an ota update and update syslinux config, grub config and fstab. The ota update would need a flag file, as would a new build.
For the time being, it will work.

x86 boot improvement & initial cubox-i support

---

scripts/volumioconfig.sh
volumio/bin/firststart.sh

The host keys should not be reused between multiple devices.
This change ensures that each Volumio device have unique host keys.
If you know of a better way to do this please let me know and I change the pull request.
I have tested the change on a Raspberry Pi 3.

Generate SSH host keys on first start

---

recipes/arm.conf
recipes/arm64.conf
recipes/x86.conf
scripts/volumioconfig.sh

It's useful to have some locales, but the full set can cost as much as 60-100MB
of disk space. Use localepurge to strip this back to a minimal set (enough to
keep Perl happy) at a cost of around 3MB.
Tested using ```-b arm -d pi ``` and ```-b x86 -d sparky``` . I did not test-boot the final images, that would probably worth doing before merging this.
Closes: volumio/Volumio2#306

Install a minimal set of locales

---

scripts/volumioconfig.sh

this driver helps support WPA2 authentication with most wifi chipsets (except Edimax which is treated separately)

add driver=nl80211 in base hostapd.conf

---

scripts/volumioconfig.sh

Current setup sets Google's DNS as defaults.
This can raise privacy concerns for some users (yes Google does track usage), and prevents addressing local resources (NAS, others) with local DNS.
Proposal is to let resolv.conf use DHCP server provided DNS, and append Google ones at the end, in case initial ones fail.

Use Google DNS as fallback only

---

scripts/raspberryconfig.sh
scripts/volumioconfig.sh
volumio/etc/apt/sources.list
volumio/etc/apt/sources.list.d/raspi.list

as per https://github.com/volumio/Build/issues/102
Please check sources.list.d/raspi.list  necessary key

Complete Raspi sources

---

build.sh
scripts/bpiproconfig.sh
scripts/bpiproimage.sh

some minor fixes in build.sh and scripts/bpipro*.sh - can now directly create a bootable Banana-Pi Pro image without manual fine tuning - kept @gkkpch 's kernel for this commit

boot mgr fixed

---

scripts/initramfs/init-x86
scripts/x86image.sh
volumio/etc/udisks-glue.conf

scripts/x86image.sh uses a different filesystem label than all the other
platform setup scripts for the 'data' partition on the flash image.
To simplify the codebase, make x86 consistent with the other platforms.
The only place the label was used was in the udisks-glue.conf file, to which
it was only recently added (b0400e4baf, Do not mount volumiodata partition).
This patch reverts that change as well.

Use consistent filesystem label for volumio_data partition

---

scripts/bpiproconfig.sh
scripts/cuboxiconfig.sh
scripts/odroidc2config.sh
scripts/sparkyconfig.sh
scripts/udooneoconfig.sh
scripts/udooqdlconfig.sh
volumio/etc/apt/sources.list.x86

We continue to use ftp.nl.debian.org until we switch to stretch
According to Debian:
"The server deb.debian.org has SRV records in DNS that let apt in **stretch and later** find places."

Syncing the scripts, add ftp.nl.debian.org to x86 sources list

---

scripts/raspberryconfig.sh

Replaces #154
After more careful reading, depmod for armv7 and armv6 in each install.sh will work under armv7 QEMU
BTW: if depmod in firststart.sh was for this, then it can be safely removed (anyway a reboot is required for such change to take effect, and it does not seem firststart.sh triggers a reboot)

Adding MrEngman drivers for armv6

---

scripts/raspberryconfig.sh

rpi-update (default) **master** branch is now on 4.9.y
Use **stable** branch while volumio sits on 4.4.y

Use proper 4.4 branch for rpi-update

---

scripts/raspberryconfig.sh

This holds critical packages to prevent direct or indirect (through dependencies) installation of libraspberrypi0, raspberrypi-bootloader, raspberrypi-kernel which critically upgrades kernel & firmware files.
This may happen when installing packages such as chromium, sense-hat, python-picamera...
This change has been tested in a new build: successfully blocked such kind of installs.
Also confirmed newer Touchscreen plugin still installs fine after this change.

Pi: Block unwanted firmware & kernel updates

---

scripts/raspberryconfig.sh

Add necessary bcm2708-rpi-0-w.dtb from 4.4 stable branch
Probably won't be necessary anymore when Kernel is updated, so it's a conditional install for now
Reported working by several users in [Forum](https://volumio.org/forum/with-new-rpi-zero-t6050-20.html#p29932).
(note: uses same chipset than Pi3 so no need for new wireless firmware)

Initial support for PiZero W wireless

---

scripts/raspberryconfig.sh

Repo has changed location since recent Dropbox [policy change](https://www.raspberrypi.org/forums/viewtopic.php?p=1131942#p1131942)
Put base repo in variable in case of further changes to be more future-proof.
Tested recomposed URLs seems good now.

Pi: Fixing MrEngman repo

---

scripts/raspberryconfig.sh

This allows users to completely turn off pi3 wireless chip (even radio), by setting `dtoverlay=pi3-disable-wifi` in `/boot/config.txt`
Tested working in this [Forum thread](https://volumio.org/forum/rpi-and-wifi-dongle-t6099-10.html#p29954)
Note that as per current issue in https://github.com/volumio/Volumio2/issues/946 , i2s_dacs/index.js always overwrites existing content of `/boot/config.txt`.
This compromises any changes made into `/boot/config.txt` by users and/or possibly required by some plugins.
That issue needs a fix, so that such features can be consistently used.

Pi: add pi3-disable-wifi.dtbo

---

recipes/arm-dev.conf
recipes/arm.conf
recipes/armv7-dev.conf
recipes/armv7.conf
recipes/armv8-dev.conf
recipes/armv8.conf

[Reported working](https://github.com/volumio/Build/pull/167#issuecomment-286980405) by @chsims1 with [that addition](https://github.com/volumio/Build/pull/167#issuecomment-286470758) on Pi platform (client to Home wifi AP only, not Volumio Hotspot at this point).
Actual carl9170 driver is in kernel, but carl9170 firmware is in `firmware-linux-free` (rather than in `firmware-atheros`! )
Shall I also add package for other builds?

Add firmware for Atheros AR9170 wifi USB dongle

---

recipes/arm-dev.conf
recipes/x86-dev.conf
scripts/raspberryconfig.sh

is already in `arm.conf` recipe, so removing duplicate install in `raspberryconfig.sh`
It is also present in all other platforms recipes, except in `arm-dev.conf` and `x86-dev.conf`, so adding there too.
BTW, those latter 2 config files seem out-of-sync with other platforms -dev instances...
more sanity-check adjustments might be needed if still of use.

 CRDA install clean-up

---

scripts/raspberryconfig.sh

No change to default 4.4.9 kernel. Just adds case parameters for manual test build

PI: add 4.9.17 kernel case

---

scripts/configure.sh
scripts/raspberryconfig.sh
volumio/bin/rename_netiface0.sh
volumio/bin/wifistart.sh
volumio/etc/udev/rules.d/99-Volumio-net.rules

This PR replaces [Pi3-specific driver blacklist-based filter](https://github.com/volumio/Build/issues/150) by udev rule.
It brings several benefits:
- avoids unwanted brcmfmac/brcmutil driver loads on all Pi platforms
- prioritizes plugged-in external USB network interfaces over built-in (wlan & eth)
- generic for all platforms (+added customization for Pi built-in eth which **is** on USB)
This fix has been tested with several devices and dongles.

udev rules to prioritize network interfaces

---

scripts/raspberryconfig.sh

4.9.20 now includes up-to date pisound, allo & hifiberry DAC drivers & overlays
This change does NOT affect standard build of Volumio on 4.4.9

Pi: bump next kernel test case to 4.9.20

---

volumio/bin/hotspot.sh

Custom `hostapd-edimax` is only launched if the loaded 8192cu module driver does NOT support `cfg80211` (as with pre 4.4.13 kernel)
Indeed, since 4.4.13 Pi kernel release, 8192cu module driver has been enhanced (without changing its version number) to include `cfg80211` support, and therefore now requires standard `hostapd`.
Note: this fix does not alter operations on current 4.4.9-based Volumio, as it indeed keeps using `hostapd-edimax` as previously.
It will also work with other ARM platform according to the 8192cu driver they may use.

Hostapd-edimax use: improved compatibility

---

scripts/raspberryconfig.sh

This PR intends to refresh GPIO setup on Pi, to make it more future-proof and aligned with jessie:
- update udev rules to current jessie distribution, properly allowing userspace use of GPIOs
- leverage current [wiringpi](http://wiringpi.com/) from raspberrypi.org repo (BTW seems only used for [this](https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/i2s_dacs/scripts/iqamp-unmute.sh), we could save it eventually)
- remove defunct (and seemingly unused) [gpio-admin](https://github.com/quick2wire/quick2wire-gpio-admin)
- cosmetic tuning of other I/O groups
Has been tested by building a current ROM image (kernel 4.4.9): still operated correctly with GPIO-Buttons plugin.

Pi: GPIOs configuration clean-up

---

scripts/volumioconfig.sh

~~This Google DNS fallback is no longer necessary (and potentially conflicting) with addition of custom DNS settings in Volumio2~~
This PR is updating default DNS information (`.head` and `.tail`) to enable custom DNS settings by https://github.com/volumio/Volumio2/pull/1061:
Both PRs should be merged at same time.

Default DNS settings update

---

scripts/raspberryconfig.sh

4.9.25 includes various improvements over 4.9.20 (networking, i2s,...)
As always, this change does NOT affect standard build of Volumio on 4.4.9

Pi: bump next kernel test case to 4.9.25

---

scripts/raspberryconfig.sh

note: BRANCH is actually ignored by rpi-update when a commit# is set
Just keeping it for now still, as at some point (when support 4.4.9 depreciated) we may sync with "stable" branch?

Pi: set firmware commit reference

---

scripts/raspberryconfig.sh

Got confirmation from https://github.com/Hexxeh/rpi-firmware/ repo maintainers there's not plan to notify on drastic branches changes. Therefore we are safer to just stick to commit# while we use `rpi-update`.

Pi: give-up on KERNEL_BRANCH references

---

scripts/raspberryconfig.sh

Only modules and dtbo may be kernel-dependant.
Firmware always need to be installed.

Pi: Adding Allo Firmware independently of Kernel Version

---

volumio/bin/dynswap.sh

Was not set at boot if swap file already existed.
now always set the same way

Make sure swapiness is always set correctly (volumionext)

---

scripts/raspberryconfig.sh

no longer needed since addition of firmware-brcm80211 package on Mar 14, 2016 as per https://github.com/volumio/Build/commit/4ad9736e8ec06422fd61813fb200925e91f907ff#diff-e745f2542baf16ec9199d5c899b4900c
```
apt-file list firmware-brcm80211
firmware-brcm80211: /lib/firmware/brcm/bcm43xx-0.fw
firmware-brcm80211: /lib/firmware/brcm/bcm43xx_hdr-0.fw
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43143-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43143.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43241b0-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43241b4-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4329-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4330-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4334-sdio.bin
firmware-brcm80211: …
```

Pi: removing redundant firmware installs

---

scripts/raspberryconfig.sh

a closer look at Build log output shows `./install.sh` invocation issues command in host OS rather in qemu.
`sh install.sh` happens properly in wanted qemu environment
Checked ok with a new build.

Pi: fix mrEngman install script invocation

---

scripts/initramfs/init
scripts/vszeroimage.sh

init will default to mmcblk0 for the boot device.
On newer devices, the boot device can also be mmcblk1
This can be overruled on the boot command line with the "bootdev=" parameter.
like "bootdev=mmcblk1" (as used for for Rock64 and Voltastream0)

init script with boot device support

---

scripts/initramfs/init-x86
scripts/x86config.sh

After an update, the new boot configurations in kernel_current.tar will have different UUIDs for boot and image partition. As the configs now get unpacked over the existing ones, reboot will fail when trying to locate the 2 partitions. This fix should update the new configs with the existing UUIDs.

x86 kernel update: swap UUIDs in boot configs

---

scripts/initramfs/init-x86
scripts/x86config.sh

Error: editing the /boot/grub/grub.cfg when updating the kernel in initramsfs has no effect as the grub configuration has been built into the standalone EFI bootloader(s).
For the X86 kernel updater to work, we need to remove the embedded grub config from the EFI bootloader(s) and place it into the EFI folder. This will allow editing in initrd.

X86 Updater: separate the embedded grub config from the EFI bootloader

---

scripts/raspberryconfig.sh

Several improvements, including better support for several i2s DACs (allo, etc).
Has been also pushed as new "stable" reference branch

Pi: move to Kernel 4.9.41

---

scripts/raspberryconfig.sh

`firmware-atheros` `firmware-ralink` `firmware-realtek` `firmware-brcm80211` packages from Pi-Foundation (customized [`firmware-nonfree`](https://github.com/RPi-Distro/firmware-nonfree/blob/master/debian/control)) include brcmfmac43143, brcmfmac43430-sdio, ralink mt7601u firmware & others, that Raspian & Debian repo may not have.
Replaces #213 and fixes volumio/Volumio2#1080 and https://github.com/volumio/Volumio2/issues/588 on Pi
Checked built image contains the expected files accordingly:
```
volumio@volumio:~$ ls /lib/firmware
RTL8192E       ath6k          mt7601u.bin  rt3090.bin
RTL8192SU      av7110         mt7610u.bin  rt3290.bin
allo           brcm           mt7650u.bin  rt73.bin
ar3k           carl9170-1.fw  rt2561.bin   rtl_nic
ar5523.bin     cis            rt2561s.bin  rtlwifi …
```

Pi: use Pi-Foundation wireless firmware packages

---

scripts/raspberryconfig.sh

Digital output from all sound cards except the USB will enter a power down mode in a default of 5000 ms. TOSLINK/COAX being shutdown when idle causes issues with DACs that as relays in them such as Schiit Yggdrasil or NAD D1050. The relay triggers whenever the digital out turns on/off, causing excessive clicking noise and loss of first few seconds of music during the transition.
Adding this option will turn off the power down time and maintain digital out all the time.
See line 66 at linux/sound/soc/soc-core.c

Disable powerdown mode for digital out.

---

scripts/initramfs/init-x86
scripts/x86config.sh
scripts/x86image.sh

Plymouth is sort of working, at least consistently during boot. There are still issues with the splash resolution. Using legacy boot (syslinux) it seems to work ok and the image scales. With uefi (grub2) it also works, but sticks to 1024x768, making it look a little odd, half way up and to the left of a full HD screen. 
No idea yet why, any input welcome....

X86: Fixing a usb3.0 boot issue and improving plymouth support

---

scripts/initramfs/init

Incidentally noticed in [this forum message](https://volumio.org/forum/flac-files-play-too-fast-after-latest-update-t7596.html#p38274) seemingly after a kernel update.
linefeed is generated by simple `echo ""` (at least on busybox echo)

Typo generated in /boot/config.txt

---

scripts/initramfs/init.nextarm
scripts/rock64config.sh
scripts/rock64image.sh

Changes done on a temporary copy of init (to avoid potential regression).
The Rock64 build implements the new init changes as proposed by @DecayFI (issue #256), but has no working kernel-update capability yet for anything else than /dev/mmc0blk devices (this is still WIP).

Rock64: Inital version

---

scripts/raspberryconfig.sh

Has been flagged as "stable"  about 2 weeks ago: many fixes since .41 including few related to sound issues.
Was holding submitting it, hoping longstanding Pi3/PiZW wireless fix would emerge soon, but we should probably not hold too much on other benefits.
Note to @taudac : please make your driver available for that new version.
Can you routinely build your driver at each Hexxeh/rpi-firmware kernel release so that we can build without fearing this hard-linked dependency?

Pi: move kernel to 4.9.51

---

scripts/raspberryconfig.sh

Make TauDAC modules install files linked to `$KERNEL_VERSION` rather than hard-coded, which imposed to edit install files at each kernel change.

Pi: TauDAC modules: use $KERNEL_VERSION

---

volumio/lib/systemd/system/dynamicswap.service

Have unit consistent with swap requirements as per [freedesktop.org reference](https://www.freedesktop.org/software/systemd/man/systemd.swap.html#Default%20Dependencies).
Is cleaner for proper reboot & shutdown.
(also similar to what [LibreELEC does](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/util-linux/system.d/swap.service))
Tested ok on PiZero

Improve dynamicswap service definition

---

scripts/initramfs/init.nextarm

Whilst porting to OrangePi One and Lite devices I discovered a small bug in the `init.nextram` script which checked whether UUIDs were being used was slightly wrong which resulted in the UUID codepath being executed even when UUIDs were not being used.

Fix init.nextarm when not using UUIDs

---

scripts/raspberryconfig.sh

Now with all MrEngman drivers (i.e. add mt7612), and reducing code duplication with a loop on drivers.
Still uses MrEngman repo, awaiting for eventual local mirror structure.

Pi: improve MrEngman wifi drivers install

---

scripts/volumioconfig.sh

It is a good practice to leave /etc/sudoers to the official distro
packages, and then create specific files under /etc/sudoers.d for
adding custom configurations.
This ensures that in case of major update of the sudoers file provided
by the official package we don't lose our custom rules while still
benefitting from any major changes happening upstream.
For Volumio, this means creating a /etc/sudoers.d/volumio-user file with
all the relevant configuration.

Use sudoers.d directory for custom permissions

---

scripts/volumioconfig.sh
volumio/lib/systemd/system/hotspot.service

This addresses an issue noticed in #288, that we want hotspot.service to be controlled by wireless.js alone. Allowing systemd to start hotspot.service independently just makes things harder to debug,

Prevent systemd starting hotspot at boot

---

scripts/raspberryconfig.sh

gives precedence to connected USB-ethernet interface over built-in ethernet.
Now support all Pis with built-in smsc95xx or lan78xx
(not tested on Pi3b+)

udev filter for Pi3+ lan78xx

---

scripts/volumioconfig.sh

Reworked #307 after merge of #305.
This is preparation for removing some sudo -S calls in volumio.sh, see volumio/Volumio2#1247 (which may need to be reworked).
This has been tested against volumio.sh with the 'sudo -S' calls to these scripts reworked to just 'sudo'. "works for me", others please test.

Give sudo permissions for two volumio_commandline_client scripts - rework #307

---

scripts/raspberryconfig.sh

as per https://github.com/RPi-Distro/firmware-nonfree/commit/b518de45ced519e8f7a499f4778100173402ae43 : Improved brcmfmac BT coexistence parameters
You'll need to mirror the file from:
https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_20161130-3+rpt4_all.deb

Latest brcm80211_20161130 firmware

---

scripts/odroidxu4config.sh
scripts/odroidxu4image.sh

- Enabled boot from SD, now supporting Odroid HC1 and HC2.
- Switched to kernel 4.19 LTS
- Improved native DSD (DSD-direct) support, backported from kernel 4.19

Odroid XU4/HC1/HC2: Kernel 4.14 LTS, Improved native DSD support

---

build.sh
scripts/primoconfig.sh
scripts/primoimage.sh

Currently the only difference is the kernel with a fix for the DAC frequency problems. Primo uses our corrected DAC driver with kernel version 4.4.132, while the tinkerboard remains on kernel 4.4.71+ until Asus corrects the DAC drivers they support.

Asus: separate primo from tinkerboard

---

build.sh

Especially `multistrap`!
After quite some head scratching as to why my images weren't booting, scrutinised the build process in more detail to discover multistrap was failing. 
This would make errors like #348 easier to catch.

Exit build script on failures

---

volumio/opt/vc/bin/dtoverlay-post
volumio/opt/vc/bin/dtoverlay-pre

If the user's shell is set to e.g. fish, running the scripts result in an error like:
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
fish: which lxpanelctl >/dev/null 2>&1 && lxpanelctl alsastop >/dev/null
This change ensures that the command is run in bash as well, as specified in the shebang line, and not in the custom user shell.

Run CMD in bash and not in user's standard shell

---

scripts/raspberryconfig.sh
volumio/bin/firststart.sh

I suggest to add the include option `#include userconfig.txt` to /boot/config in order to solve issue #347 "System Update does not preserve /boot/config.txt changes (crossref)" respectively [#1568](https://github.com/volumio/Volumio2/issues/1568).
The user would have to fill the predetermined file (/boot/userconfig.txt) with his additions and remove the comment statement (#) from the include option in /boot/config.txt.
On an update the include option would be commented out again (by re-applying the vanilla config.txt) but the additions in userconfig.txt would be preserved. That way the update process would not have to deal with backing up and restoring user made changes and can remain unchanged. Furthermore it would be assured that the system boot will not fail because of user made …

Solution to issue #347 and #1568

---

build.sh

`VOLUMIO_FE_VERSION` in `/etc/os-release` was empty.
Reason:
Folder `/volumio/http/www/.git` was deleted before `git ... rev-parse HEAD`
So I moved the deletion after writing version information to `/etc/os-release`.

moved 'rm -rf .git' after 'git rev-parse HEAD'

---

scripts/raspberryconfig.sh

https://github.com/RPi-Distro/firmware-nonfree/issues/8#issuecomment-615339218
(need to get file from https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_20190114-1+rpt6_all.deb )

Pi: update brcm firmware & improve BT coexistence

---

volumio/etc/udev/rules.d/92-gpio.rules

Corrected wrong line feeds causing 92-gpio.rules to fail with error message `invalid key/value pair in file /etc/udev/rules.d/92-gpio.rules on line 1,starting at character 226 (' ')`.

Repair 92-gpio.rules

---

volumio/bin/volumiologrotate

after installation of squeezeboxserver i got error in journalctl because your logrotate doesn't recognize subfolders like /var/log/squeezeboxserver in LOG_FOLDER (/var/log/).
no idea if find is the best solution to only check files but it solves the error.

fix volumiologrotate if subfolders exist inside LOG_FOLDER.

---

volumio/bin/dynswap.sh

as per issue https://github.com/volumio/Build/issues/399
`/data` is part of overlay, and can not be used for swap.
`swapon: /data/swapfile: swapon failed: Invalid argument`
Mount partition into new `/swap`, and enable swapfile as before

fix dynswap.sh

---

recipes/devices/families/kvims.sh
recipes/devices/families/x86.sh
recipes/devices/motivo.sh
recipes/devices/odroidn2.sh
recipes/devices/orangepilite.sh
recipes/devices/tinkerboard.sh

By setting `BOOT_USE_UUID=yes` in the device file, `makeimage` sets the `BOOT_FS_SPEC` to use the UUID (instead of default `/dev/mmcblk0p1`) that is then later written to the fstab by `chrootconfig`   https://github.com/volumio/Build/blob/df8342796ea597e131cfe23ecc7c7ff2bd30c74d/scripts/makeimage.sh#L183-L185
https://github.com/volumio/Build/blob/df8342796ea597e131cfe23ecc7c7ff2bd30c74d/scripts/volumio/chrootconfig.sh#L25-L31
Also found a few copypasta syntax issues that were preventing builds, and for good measure ran a formatter on everything to catch the rest. :-)
I had set up a [CI to catch these things back on `ashthespy/VolumioOS`](https://github.com/ashthespy/VolumioOS/runs/1670528502?check_suite_focus=true#step:3:97) --  will also try and set up an auto formatter so we don't get …

Tweak boards to use `BOOT_USE_UUID`, fix some syntax errors..

---

recipes/devices/families/kvims.sh
recipes/devices/families/x86.sh
recipes/devices/odroidn2.sh
scripts/helpers.sh
scripts/makeimage.sh
scripts/volumio/chrootconfig.sh

Building upon the discussion in db7b9568d6b7115d39086b3ea4311bedb99cb4c9, tweaked the error handling for our device template functions. 
Errors in `device_chroot_xxx` device functions were caught previously because `chroot` would propagate any error up catch the trap.  But device functions like `write_device_xx` wouldn't given the way Bash handles functions environments by default. 
We now set the  `-o errtrace` flag to explicitly force errors in functions to catch traps as well.
Also tried to have the errors be a little more informative to quickly track down where they arise. The stack trace is quite  rudimentary - it isn't the best (even worse inside `chroot`), but it is something ;-) 
Some tests: 
```diff
diff --git a/recipes/devices/families/kvims.sh …
```

Tweak error handling for device script functions.

---

scripts/makeimage.sh

Should now let you build form the same `platform-${DEVICEFAMILY}` without having to delete and re clone it each time..

Tweak platform tarball handling for platform families

---

build.sh

Currently, we were fetching the Volumio FE/BE again even if we just built a fresh base.. Now we check if we are using a prior tarball, and only then re-fetch. So we should shave a few seconds off build time when building along with a base..
PS: Also changed the default behaviour of the undocumented `UPDATE_VOLUMIO` to yes.

Remove redundant Volumio BE/FE clone on fresh rootfs builds

---

scripts/config.sh
volumio/etc/apt/sources.list.arm
volumio/etc/apt/sources.list.armv7
volumio/etc/apt/sources.list.armv8
volumio/etc/apt/sources.list.x86

https://wiki.debian.org/DebianGeoMirror states that httpredir has been discontinued.
I've tested this only by building a volumio image; not sure what further testing is required.

Use deb.debian.org instead of httpredir.d.o

---

build.sh

Added the lint hooks back..
However, today I think it might be easier/nicer to instead setup a simple CI that formats all PRs.. Instead of getting contributors to mess with white space.. 
On a side note - I see I set my soft tabs to 2 spaces. Resulting in what the build scripts look like. Do you want me to change to 4?

 Add BE precommit hooks

---

recipes/base/VolumioBase.conf
scripts/volumio/configure.sh
scripts/volumio/volumioconfig.sh
volumio/etc/triggerhappy/triggers.d/audio.conf

Cherry picked 859858f6eee0b4de0db7aa9e3dc878e08afe0fa3 into our tree..
Not sure which devices use it -- please do test! :-)
Fixes #386 (in new build that is)

Triggerhappy instead of xbindkeys for media controls

---

build.sh
recipes/base/VolumioBase.conf
scripts/makeimage.sh
scripts/volumio/finalize.sh
scripts/volumio/volumioconfig.sh

-- Removing a lot of redundant multistrap config bits (like libraries, dummy packages) 
since we don't set [`omitrequired=true`](https://manpages.debian.org/testing/multistrap/multistrap.1.en.html#Restricting_package_selection), we can remove the libraries that are linked to installed packages.
>If the OmitRequired option is set to true, these packages will not be added - whilst useful, this option can easily lead to a useless rootfs. Only the packages specified manually in the configuration files will be used in the calculations - dependencies of those packages will be added but no others.
This then leaves extra libs that are really needed.  e.g `libavahi-compat-libdnssd-dev` for the [`mdns`](https://www.npmjs.com/package/mdns#installation) node package utilised by the back end. Ideally …

Cleanup rootfs

---

recipes/devices/README.MD
recipes/devices/cuboxp.sh
recipes/devices/families/kvims.sh
recipes/devices/families/odroids-earlygen.sh
recipes/devices/families/odroids-newgen.sh
recipes/devices/families/pine64.sh
recipes/devices/families/x86.sh
recipes/devices/kvim1.sh
recipes/devices/kvim2.sh
recipes/devices/kvim3.sh
recipes/devices/mp1.sh
recipes/devices/nanopineo2.sh
recipes/devices/nanopineo3.sh
recipes/devices/odroidc1.sh
recipes/devices/odroidc2.sh
recipes/devices/odroidc4.sh
recipes/devices/odroidn2.sh
recipes/devices/odroidxu4.sh
recipes/devices/orangepilite.sh
recipes/devices/pi.sh
recipes/devices/pine64base.sh
recipes/devices/pine64plus.sh
recipes/devices/pine64solts.sh
recipes/devices/rock64.sh
recipes/devices/rockpis.sh
recipes/devices/tinkerboard.sh
recipes/devices/x86_amd64.sh
recipes/devices/x86_i386.sh

Added some placeholders, should be updated to reflect [`Device table`](https://github.com/volumio/Build/blob/volumioOS/recipes/devices/README.MD#devices) from 2401d04 
Btw, while looking at our device support table, I released current build system don't support multi device build ergonomically yet e.g `Kvims` `Orangepi{one|lite|pc}` -- something that needs to be worked on..

Synchronise device scripts

---

scripts/volumio/configure.sh

Didn't push everything in #470.
Strangely the `mpd.conf` file was being copied twice for some reason, once in `build.sh` that was removed in 20e3c8c
and then again in `configure.sh` that this cleans up..

Cleanup more redudndant `mpd.conf`

---

recipes/devices/cuboxp.sh
recipes/devices/families/kvims.sh
recipes/devices/families/odroids-earlygen.sh
recipes/devices/families/odroids-newgen.sh
recipes/devices/families/pine64.sh
recipes/devices/families/x86.sh
recipes/devices/nanopineo2.sh
recipes/devices/nanopineo3.sh
recipes/devices/odroidxu4.sh
recipes/devices/orangepilite.sh
recipes/devices/pi.sh
recipes/devices/rock64.sh
recipes/devices/rockpis.sh
recipes/devices/tinkerboard.sh
recipes/devices/vszero.sh
scripts/makeimage.sh

Fixing an old `TODO`
-- Add a `device_image_tweaks_post`  to the templates that is invoked by `makeimage` post the chroot stuff, before `finalize` to run any device specific tweaks.
-- Use this to run `mkimage` outside the chroot, so that we don't need to install `u-boot-tools` during device level chroot configuration. 
-- Add `UINITRD_ARCH` into device templates so it's explicit if our device has an `armv7` or `amv8` cpu. 
Can also go ahead and update the rest of the devices, but can't test them..

Streamline `uInitrd` creation

---

recipes/base/VolumioBase.conf
recipes/base/arm.conf
recipes/base/armv7.conf
recipes/base/armv8.conf
recipes/base/x86.conf
scripts/config.sh

This commit switches MPD installation to use the apt repository recommended by the MPD team because it is kept up to date with the MPD release. 
The version in buster is several years old and does not work when the multiroom is enabled (even when multiroom isn't being used).
Note that there are two repositories, one which has `amd64` binaries, and one which has `armhf` binaries. The `armhf` binaries are all raspbian compatible (i.e. compiled for armV6 floating point) but still work on non raspbian armV7 targets (tested on tinkerboard).

Pull in the latest MPD

---

recipes/devices/families/x86.sh

This one is good to go, it will enable some of the Intel Atom sound devices (rt5640/rt5651 and es8316)

Revert to Alsa UCM from Alsa UCM2

---

recipes/devices/families/x86.sh

It seems we were running after the facts.
Our own ucm folder is no longer needed with buster as the installation of Alsa tools already appears to store the defaults in /usr/share/alsa/ucm. Our (old jessie) version was just overriding and disabling Intel Atom soc audio.

Fix ucm default issue

---

scripts/volumio/install-kiosk.sh

When (re)booting, Chromium will display this startup message when it detects a mismatch between profile and hostname.
This mismatch occurs each time as a result of a Player Name (hostname) change in the previous session.

Fix Chromium 'Unlock Profile and Relaunch' startup message

---

recipes/devices/README.MD
recipes/devices/families/orangepi_h3.sh
recipes/devices/orangepione.sh
recipes/devices/orangepipc.sh

Finalise support for OrangePiOne and OrangePiPC.
Bumped from the sunxi's 5.4 to 5.10.y kennel and my OpiLite still works fine. 
The Opi One and PC I don't have to test, but it looks like @Vyacheslav-S has already [provided some test Buster images](https://community.volumio.org/t/volumio-debian-buster-beta-orange-pi-images/44826) although I am unsure with which platform files.

Add OrangePi H3 based family

---

scripts/initramfs/init.x86

This fix prevents an unchanged glob to be used as a device name, which causes this error at startup with installations which boot from eMMC or NVMe installed with no usb stick or other usb devices attached:
```
lsblk: /dev/sd[a-z]: not a block device
```

init.x86: only expand glob to valid device names, return null otherwise

---

recipes/base/x86.conf
recipes/devices/families/x86.sh
scripts/initramfs/init.x86

Enable jack detection for Intel Atom RT5640-based sound devices. 
It allows switching between speaker and headphones when plugging/unplugging the headphone jack

Enable rt5640 jackdetect

---

recipes/devices/pi.sh

This PR is re-created as discussed in the previously-closed one: [PR#512](https://github.com/volumio/Build/pull/512). The referred archive is manually collected for now, and we may need a CI/CD system for our best interest.

Fetching pre-built artifacts for wm8960 DAC

---

recipes/devices/pi.sh

This should fix things -- please also see #472 and test both!

[raspberry] Don't overwrite `userconfig.txt` on OTA

---

volumio/bin/firststart.sh

Few questions though, 
-- Does this script run on every upgrade? Or only on the first time the image is flashed and run? 
-- Why are we appending, shouldn't it rather check if the file exists and if not create it?

Create userconfig.txt on firstart only on Raspberry devices
