volumio/Build

build.sh
scripts/initramfs/init
scripts/initramfs/mkinitramfs-custom.sh
scripts/odroidcconfig.sh
scripts/odroidcimage.sh

First version of an Odroidc build

Add Odroidc platform build

---

recipes/arm-dev.conf
recipes/arm.conf

removed empty folder

---

build.sh

add "arm" after -b in the example

---

scripts/configure.sh
volumio/etc/shairport-sync.conf.tmpl

Configuration script copy standard shairport file AND set permissions

configuration file for shairport

---

volumio/etc/netplug/netplug

This should restore network on volumio (plus enabling the NETPLUG systemd service,  which you should have already done)

wireless and lan together

---

scripts/odroidx2image.sh
scripts/odroidxu4image.sh
scripts/x86.sh

Now all odroids and x86 follow the standard

Common image naming

---

volumio/etc/dhcp/dhclient.conf
volumio/etc/network/interfaces

In my build I also removed the file wpa_supplicant.service, it's not used anywhere so it should be safe to leave it and safe to remove...

Network configuration

---

scripts/odroidc2image.sh
scripts/odroidcconfig.sh

Needs old platforms-O folder to be deleted

Newest C1/ C2 kernels with dac drivers as loadable modules

---

volumio/etc/samba/smb.conf

small correction with data path comment

---

recipes/x86 (hybrid grub uefi).conf
recipes/x86-dev (hybrid grub uefi).conf
recipes/x86-dev.conf
scripts/initramfs/init-x86
scripts/x86 (grub hybrid uefi).sh
scripts/x86config (grub hybrid uefi).sh
scripts/x86config.sh

Finally a first properly working hybrid X86 version.
It uses Syslinux for booting Legacy BIOS and Grub 2 for EFI. 
It covers both 32bit and 64bit EFI bootloaders with the 32bit kernel.
Tested on VirtualBox 5.0.24, 32bit and 64bit host, with 32bit and 64bit UEFI, then Asus 64bit Notebook,  HP 32bit Notebook (old, never booted with grub), 64bit Gigabyte motherboard (own build) and an Intel NUC. 
The fsck problems have been fixed in x86.sh after unmounting the vfat boot partition.
The cause is creating a syslinux mbr without having a backup boot sector (not sure yet why this happens, may be an incompatibility between syslinux and gpt partitions). Would not have done any harm as we do not really need the backup boot sector, the fsck message just looked ugly at boot time

Syslinux for BIOS, Grub for UEIFI and OpenBox/Chromium for Volumio kiosk

---

README.md
scripts/x86config.sh
volumio/lib/systemd/system/firststart.service

Added a service for starting Kiosk mode

Starting Volumio Kiosk with systemd, small additions and a typo correction

---

README.md
build.sh

I have been experimenting with building and noticed a few small things that could be improved.

cleanups in build.sh

---

recipes/x86.conf
scripts/initramfs/init-x86
scripts/initramfs/mkinitramfs-custom.sh
scripts/x86.sh
scripts/x86config.sh

You may want to wait with this as solaar74 reported problems on reboot after a successful first start.
Not sure yet if this is boot-related, it fails on mounting devices AFTER initrd

Fixed moving GTP partition backup tabled (initrd)

---

scripts/cuboxiimage.sh
scripts/odroidc1image.sh
scripts/odroidc2image.sh
scripts/odroidxu4image.sh
scripts/raspberryimage.sh
scripts/sparkyimage.sh
scripts/x86.sh

Start addressing https://github.com/volumio/Volumio2/issues/335.

Calculate md5 checksums of final image

---

scripts/bbbconfig.sh
scripts/bbbimage.sh
scripts/initramfs/init

initial support for BBB

---

recipes/x86.conf

consistency with other recipes

Use repo redirector

---

volumio/bin/dynswap.sh

Signed-off-by: Earl Chew <earl_chew@yahoo.com>

[dynswap.sh] Only active swap file if there are no other swap areas

---

recipes/arm-dev.conf
recipes/arm.conf
recipes/minimal.conf
recipes/x86-dev.conf

replaces https://github.com/volumio/Build/pull/122 and https://github.com/volumio/Build/pull/124

Update recipes sources repo

---

build.sh
volumio/bin/wireless.js

We should not do a last minute change to Debian, better wait until fully tested.

Use Raspbian for Sparky (to avoid unknown problems)

---

build.sh
recipes/armv7.conf
recipes/armv8-dev.conf
scripts/bpiproconfig.sh
scripts/bpiproimage.sh
scripts/pine64image.sh
volumio/bin/wireless.js

Banana scripts are untested but close, will continue when I have a unit.

Small wireless, architecture and Banana Pro script additions

---

scripts/raspberryconfig.sh

force_turbo=1 is meant for config.txt only

Remove force_turbo=1 from cmdline.txt (is a config.txt thing only)

---

scripts/bpiproimage.sh

choice between @gkkpch Kernel and chrismade kernel by commenting the respective lines in bpiproimage.sh files - for more details on chrismade kernel (WLAN driver, power save, sndspdif etc) see GitHub chrismade/banana-pi-pro

choose kernel in BananaPi Pro image script by commenting in-out

---

scripts/raspberryconfig.sh

as per https://github.com/volumio/Build/issues/103
(plus remove linefeed in   /etc/apt/sources.list.d/raspi.list )

Raspberry: streamlining /etc/modules

---

README.md
build.sh
scripts/armbianconfig.sh
scripts/armbianimage.sh
scripts/initramfs/init_armbian
scripts/upgrade_armbian.sh

in addition to native images in Volumio Build users have now a fallback option to create images based on armbian (so far tested for A20 based boards, may also work for others)

armbian image support in volumio build

---

scripts/raspberryconfig.sh
volumio/bin/firststart.sh

as per [this](https://github.com/volumio/Build/commit/d318ab64f9ed66b07d19632815ccc9f9f9b95ec7#commitcomment-21141180)

Optimizing depmod

---

build.sh

-bmaster vs -b master in Volumio2 clone

improper git option (typo)

---

scripts/armbianconfig.sh
scripts/bbbconfig.sh
scripts/bpim2uconfig.sh
scripts/bpiproconfig.sh
scripts/cuboxiconfig.sh
scripts/odroidc1config.sh
scripts/odroidc2config.sh
scripts/odroidx2config.sh
scripts/odroidxu4config.sh
scripts/pine64config.sh
scripts/raspberryconfig.sh
scripts/sparkyconfig.sh
scripts/udooneoconfig.sh
scripts/udooqdlconfig.sh

just a good practice
https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/

protect /dev/shm

---

scripts/raspberryconfig.sh

case switch to allow testing Build with different kernel versions

Pi: prepare to test new kernels

---

scripts/raspberryconfig.sh

One remains at the end of the script.

Pi: remove duplicate apt cache cleanup

---

scripts/raspberryconfig.sh

provided by raspberrypi-sys-mods package

Pi: apply standard Jessie system configuration (volumionext)

---

recipes/arm-dev.conf
recipes/arm.conf
recipes/armv7-dev.conf
recipes/armv7.conf
recipes/armv8-dev.conf
recipes/armv8.conf
recipes/minimal.conf
recipes/x86-dev.conf
recipes/x86.conf

required for https://github.com/volumio/Volumio2/pull/1231

add  minizip for plugin install

---

scripts/initramfs/init

Default: echo to /dev/kmsg
cmdline option "use_kmsg=no" will override default (no echo to /dev/kmsg)

initramfs: add option to echo to /dev/kmsg

---

scripts/raspberryconfig.sh

Pi: superfluous apt-get update

---

scripts/vszeroimage.sh

volumio-remote-updater service does not start, needs to be checked

Pre-release version, with open issues

---

scripts/initramfs/init
scripts/initramfs/init-x86

reverted fix in initrd, continue with init-x86 first and come back to init later

revert arm init change, modify init-86

---

scripts/sparkyconfig.sh

Allo Relay Attenuator support for Sparky

Allo RA support for Sparky

---

scripts/pine64image.sh
scripts/sopine64image.sh

Using the gkkpch repo, switching back after building the dev versions

Enabling support for sopine64 & pine64LTS

---

scripts/volumioconfig.sh

I hope this helps for the Kodi plugin

Add tv-service alias

---

scripts/initramfs/init.nextarm
scripts/tinkerconfig.sh
scripts/tinkerimage.sh

- modified extlinux.conf
- UUID support in kernel command line

Tinker S: single image for booting eMMC and SD

---

build.sh
scripts/nanopineo2config.sh
scripts/nanopineo2image.sh
scripts/nanopineoconfig.sh
scripts/nanopineoimage.sh

Platform files will be download from my repository

Buid scripts for FriendlyArm NanoPi-Neo, -Neo Air, Neo2 devices

---

scripts/raspberryconfig.sh

as per [this](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&p=1271993#p1271965).
Should in particular fix https://github.com/volumio/Build/issues/291 for good.

Pi: update MrEngman drivers location

---

scripts/x86image.sh

- Adding Firmware for Intel SST Audio

Support for experimental X86/ Intel CherryTrail Audio

---

scripts/raspberryconfig.sh

latest support for Pi3/Pi0W and Pi3+

include all latest brcm firmware

---

scripts/raspberryconfig.sh

Pi3b+: try 4.14.29

---

build.sh
scripts/orangepiconfig.sh
scripts/orangepiimage.sh

This initial cut supports the OrangePi Lite and One devices.

Support for OrangePi devices

---

scripts/raspberryconfig.sh

Pi: fix for 4.14.37 case switch

---

scripts/raspberryconfig.sh

more fixes and few specific for Pi3b+ (ethernet, firmware,...)

PI: kernel up to 4.14.42

---

scripts/armbianimage.sh

Keeping the build scripts for the time being, who knows...

Armbian builds: suspend support (not deleting yet)

---

scripts/volumioconfig.sh

Some warnings and fixes found by using `set -e`. 
Maybe a good idea to turn it on even in this script?

Fixes in `volumioconfig.sh`

---

scripts/aml805armv7image.sh
scripts/aml812armv7image.sh
scripts/aml9xxxarmv7image.sh
scripts/cuboxiimage.sh
scripts/nanopi64image.sh
scripts/nanopineo2image.sh
scripts/nanopineoimage.sh
scripts/odroidc1image.sh
scripts/odroidc2image.sh
scripts/odroidn2image.sh
scripts/odroidx2image.sh
scripts/pine64image.sh
scripts/raspberryimage.sh
scripts/rock64image.sh
scripts/sopine64image.sh
scripts/sparkyimage.sh
scripts/tinkerimage.sh
scripts/udooneoimage.sh
scripts/udooqdlimage.sh
scripts/vszeroimage.sh
scripts/x86image.sh

Fix missing md5 checksums on some images

---

.travis.yml

Fixes some of the recent Travis failures

Use Travis's integrated `shellcheck`

---

scripts/raspberryconfig.sh

need to add the others too (PATCH ones, check TAUDAC)

adding some Pi4 v7l drivers (Mr Engman)

---

scripts/raspberryconfig.sh

HDMI sound fix
Hifiberry DAC+DSP soundcard driver 
...and many other stuff

PI kernel 4.19.75

---

volumio/bin/wireless.js

This is the other shoe from #288 - what to do when no wireless interface is available. I'll close that PR now.

Handle missing wlan0

---

build.sh

Auto check and install prerequisite packages.

Auto check and install prerequisite packages

---

scripts/raspberryconfig.sh

Add compiled module and overlay for BassOwl-HAT

include Module and Overlay for BassOwl-HAT

---

build.sh
scripts/makeimage.sh

As part of the effort to clean up all the flags scattered around.. :-D

Remove hard paths, allow setting output location

---

README.md

This should now be a thorough list of requirements..

[Doc] Update requirements for Buster host, and remove outdated parts

---

recipes/devices/raspberry.sh

Super quick and dirty -- will refactor this later!
Fixes #436

[raspberry] Fetch node installer from repo

---

recipes/devices/families/odroids-earlygen.sh
scripts/makeimage.sh

This is useful to exclude ext4 metadata checksums on older kernels..
@gkkpch What do you think? Too much flexibility?

Allow for device specific extra options for file system creation.

---

build.sh

This should cover things as described by @xipmix -- or did I miss something? 
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b armv8 -d raspbberypi5
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <raspbberypi5> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -d raspbberypi5
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <raspbberypi5> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```
```bash …
```

Exit early if an unsupported device is passed in

---

scripts/config.sh
scripts/makeimage.sh

Streamline init_updater installation

---

recipes/devices/README.MD

Overview of the supported devices. I'd like to extend this documentation w.t.r the device template, and what all the variables in there are, and how they are used. But that will come later, once things are settled with Buster.
Also wondering if it might be a good idea to indicate devices that are officially supported, and devices that are community efforts.. 
Closes #445

Add some documentaton about devices

---

recipes/devices/pi.sh

Since got fed up of having to check what the latest kernel was from [`raspberrypi/firmware`](https://github.com/raspberrypi/firmware), [`raspberrypi/linux`](
https://github.com/raspberrypi/linux) and [`Hexxeh/rpi-firmware`](https://github.com/Hexxeh/rpi-firmware). 
Of course, turned off by default, and with a warning that things ~will~might break..

[raspberry] Add an option to fetch the latest kernel

---

recipes/devices/pi.sh

-- Added back the ability to switch branches
-- Remove separate firmware installation
Not sure if this is still relevant but back in https://github.com/volumio/Build/commit/cac931eda81b99ff610cf0e9252dffb61388371a the ability to update firmware files as explicitly added. 
But then later down the line, https://github.com/volumio/Build/pull/191 hashes were synced, so that both kernel and firmware are obtained from the same SHA. 
Since we are now picking the firmware and kernel in sync with the same SHA, we can get rid of the second invocation of `rpi-update`
From build logs we see that it doesn't do anything, but we can remove it to remove confusion..
```
[ ---- ] Adding kernel 5.10.3 using rpi-update  
*** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
!!! …
```

[raspberry] Allow rpi-update to switch branches, remove obsolete firmware installation step

---

README.md
build.sh

Nothing serious, just making things a bit more consistent..

Tweak docs

---

recipes/devices/families/x86.sh

I suggest this one to replace #473

X86: fix kernel image name to 'vmlinux'

---

scripts/odroidc4image.sh

fix for platform changes because of buster migration

odroidc4image.sh: fix for platform changes because of buster migration

---

scripts/initramfs/init.x86

init.x86: fix glob issue

---

recipes/devices/pi.sh

Revert "[raspberry] Don't overwrite `userconfig.txt` on OTA"
